[package]
name = "albatross"
description = "Set of algorithms for personal usage."
version = "0.1.0"
edition = "2021"

[dependencies]
slotmap = "1"

tap = "1"
fixed = { version = "1", features = ["num-traits"] }

thiserror = "1"

derive_more = "0.99"
enum-as-inner = "0.6"

typenum = "1"
